# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Party-DJ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Party-DJ

  target 'Party-DJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Party-DJUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
